---
version: "3"
services:
  beancount:
    image: beancount:20211031
    container_name: beancount
    hostname: xps-9560
    volumes:
      - /opt/syncthing/beancount:/beancount
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8184:8184
    restart: unless-stopped
